### ISSUE TITLE
The `include/umf/proxy_lib_new_delete.h` file contains extra ";"

### ISSUE THREAD

**Issue by vinser52** [oneapi-src/unified-memory-framework#512]
The `include/umf/proxy_lib_new_delete.h` file contains extra ";".

There is already a fix for this issue: #510.

But before merging @bratpiorka suggested investigating why the CI did not catch the issue and fix the CI. My early investigation suggests that our CI run build on the Ubuntu 20.04 with `-DUMF_BUILD_SHARED_LIBRARY=OFF` while the issue is reproduced only when `-DUMF_BUILD_SHARED_LIBRARY=ON` - not sure why it is matter.
 

## Environment Information

- UMF version (hash commit or a tag):                         main branch
- OS(es) version(s):                                          Ubuntu 20.04
- kernel version(s):                                          5.4.0-146-generic
- compiler, libraries, and other related tools version(s):    gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0

## Please provide a reproduction of the bug:

Just try to build UMF with the following options:
```
cmake .. -DUMF_BUILD_LIBUMF_POOL_SCALABLE=ON -DUMF_BUILD_SHARED_LIBRARY=ON
make -j
```

## How often bug is revealed:

always

## Actual behavior:

Build fails because of extra ‘;’ in the  `include/umf/proxy_lib_new_delete.h` file:
```
In file included from /home/svinogra/unified-memory-framework/test/test_proxy_lib.cpp:14:
/home/svinogra/unified-memory-framework/include/umf/proxy_lib_new_delete.h:71:52: error: extra ‘;’ [-Werror=pedantic]
   71 | void operator delete(void *p) noexcept { free(p); };
      |                                                    ^
/home/svinogra/unified-memory-framework/include/umf/proxy_lib_new_delete.h:72:54: error: extra ‘;’ [-Werror=pedantic]
   72 | void operator delete[](void *p) noexcept { free(p); };
      |                                                      ^
/home/svinogra/unified-memory-framework/include/umf/proxy_lib_new_delete.h:99:2: error: extra ‘;’ [-Werror=pedantic]
   99 | };
      |  ^
/home/svinogra/unified-memory-framework/include/umf/proxy_lib_new_delete.h:103:2: error: extra ‘;’ [-Werror=pedantic]
  103 | };
      |  ^
/home/svinogra/unified-memory-framework/include/umf/proxy_lib_new_delete.h:119:2: error: extra ‘;’ [-Werror=pedantic]
  119 | };
      |  ^
/home/svinogra/unified-memory-framework/include/umf/proxy_lib_new_delete.h:124:2: error: extra ‘;’ [-Werror=pedantic]
  124 | };
      |  ^
In file included from /home/svinogra/unified-memory-framework/test/memoryPoolAPI.cpp:18:
/home/svinogra/unified-memory-framework/include/umf/proxy_lib_new_delete.h:71:52: error: extra ‘;’ [-Werror=pedantic]
   71 | void operator delete(void *p) noexcept { free(p); };
      |                                                    ^
/home/svinogra/unified-memory-framework/include/umf/proxy_lib_new_delete.h:72:54: error: extra ‘;’ [-Werror=pedantic]
   72 | void operator delete[](void *p) noexcept { free(p); };
      |                                                      ^
/home/svinogra/unified-memory-framework/include/umf/proxy_lib_new_delete.h:99:2: error: extra ‘;’ [-Werror=pedantic]
   99 | };
      |  ^
/home/svinogra/unified-memory-framework/include/umf/proxy_lib_new_delete.h:103:2: error: extra ‘;’ [-Werror=pedantic]
  103 | };
      |  ^
/home/svinogra/unified-memory-framework/include/umf/proxy_lib_new_delete.h:119:2: error: extra ‘;’ [-Werror=pedantic]
  119 | };
      |  ^
/home/svinogra/unified-memory-framework/include/umf/proxy_lib_new_delete.h:124:2: error: extra ‘;’ [-Werror=pedantic]
  124 | };
      |  ^
```

## Expected behavior:

Build successes.

## Details

The issue is reproduced only when `-DUMF_BUILD_SHARED_LIBRARY=ON` but our CI run build on the Ubuntu 20.04 with `-DUMF_BUILD_SHARED_LIBRARY=OFF`

## Additional information about Priority and Help Requested:

PR #510.

Requested priority:  Meduim

**Comment by bratpiorka** [comment]
fixed by https://github.com/oneapi-src/unified-memory-framework/pull/518
